database:
    - name: mysetedb
      plan: free
      databaseName: naru1234
      user: naru5678
services:
    - type: web
      plan: free
      name: naru9012
      runtime: python
      buildCommand: "./build.sh"
      startCommand: "python -m gunicorn bookproject.asgi:application -k uvicorn.workers.UvicornWorker"
      envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: mysitedb
            property: connectionString
        - key: WEB_CONCURRENCY
          value: 4